[project]
name = "flake8_qiskit_migration"
version = "0.1.0"
dependencies = [ "flake8", ]

[project.entry-points."flake8.extension"]
QKT100 = "flake8_qiskit_migration.plugin:Plugin"

[project.scripts]
flake8-qiskit-migration = "flake8_qiskit_migration.command:cli"
